//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.21.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace SharedTypes.NET
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.21.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class ContactSearch 
    {
        [Newtonsoft.Json.JsonProperty("SearchTerm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SearchTerm { get; set; }
    
        [Newtonsoft.Json.JsonProperty("PageNumber", Required = Newtonsoft.Json.Required.Always)]
        public int PageNumber { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
    
        public static ContactSearch FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<ContactSearch>(data);
        }
    
    }
}